version: '3.8'

volumes:
  static:
  media:

services:
  python: &python
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file: 
      ./docker/python/python.env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8000:8000
    command: gunicorn -w 4 FakeCSV.wsgi -b 0.0.0.0:8000
    depends_on: 
      - postgres

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8080:80
    depends_on:
      - python

  postgres:
    image: postgres:12.4
    command: postgres -c port=5430
    env_file: ./docker/postgres/db.env
    ports:
      - 5430:5430

  redis:
    build: 
      context: .
      dockerfile: docker/redis/Dockerfile
    restart: always
    ports:
      - 6380:6380
    command: redis-server /usr/local/etc/redis/redis.conf

  celery:
    <<: *python
    command: celery -A FakeCSV worker -l INFO
    ports: []
    restart: always
    depends_on:
      - redis
      - postgres
