# Generated by Django 3.1.7 on 2021-03-02 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_row', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready')], default='Processing', max_length=50)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('file', models.FileField(null=True, upload_to='data_sets/')),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Full name', 'Full name'), ('Color', 'Color'), ('City', 'City'), ('Company', 'Company'), ('Phone_number', 'Phone number'), ('Integer', 'Integer'), ('Country', 'Country'), ('Month', 'Month')], max_length=100)),
                ('start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
